src/SurveyManager/SurveyManager.Presentation.MVC4/Models/ModuloViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SurveyManager.Presentation.MVC4.Models
{
    public class ModuloViewModel
    {
        public Guid BlocoId { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Model.Implementation;
using SurveyManager.Domain.Repository;
using SurveyManager.Presentation.MVC4.Models;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ModulosController : Controller
    {
        private Contexto db = new Contexto();
        private readonly ModuloRepositorio ModulosRep = new ModuloRepositorio();

        // GET: Modulos
        public ActionResult Index()
        {
            return View(ModulosRep.ListarTodos().ToList());
        }

        public ActionResult ActionDeVoltar(string returnUrl)
        {
            if (returnUrl != "")
                return Redirect(returnUrl);
            else
                return null;
        }

        // GET: Modulos/Create
        public ActionResult Create(Guid blocoId)
        
        {
            ModuloViewModel modulo = new ModuloViewModel() { BlocoId = blocoId };
            return View(modulo);
        }

        // POST: Modulos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "blocoId,Nome,Codigo")] ModuloViewModel modulo)
        {
            if (ModelState.IsValid)
            {
                Bloco bloco = db.Blocos.Find(modulo.BlocoId);
                Modulo moduloDb = new Modulo()
                {
                    Id = Guid.NewGuid(),
                    Nome = modulo.Nome,
                    Codigo = modulo.Codigo
                };
                bloco.Modulos.Add(moduloDb);
                ModulosRep.Adicionar(moduloDb);
                db.SaveChanges();

                return RedirectToAction("Edit", "Blocos", new { id = modulo.BlocoId });
            }

            return View(modulo);
        }

        // GET: Modulos/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulo modulo = db.Moduloes.Find(id);
            db.Entry(modulo).Collection(b => b.Turmas).Load();
            if (modulo == null)
            {
                return HttpNotFound();
            }
            return View(modulo);
        }

        // POST: Modulos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Codigo")] Modulo modulo)
        {
            if (ModelState.IsValid)
            {
                ModulosRep.Atualizar(modulo);
                ModulosRep.SalvarTodos();

                return RedirectToAction("Index");
            }
            return View(modulo);
        }

        // GET: Modulos/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulo modulo = ModulosRep.Buscar(id);
            if (modulo == null)
            {
                return HttpNotFound();
            }
            return View(modulo);
        }

        // POST: Modulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Modulo modulo = ModulosRep.Buscar(id);
            ModulosRep.Excluir(m => m == modulo);
            ModulosRep.SalvarTodos();

            return RedirectToAction("Index");
        }

        public ActionResult List(List<Modulo> modulos)
        {
            return View(modulos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ModulosRep.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Repository;
using SurveyManager.Domain.Model.Implementation;
using SurveyManager.Presentation.MVC4.Models;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class TurmasController : Controller
    {
        private Contexto db = new Contexto();
        private readonly TurmaRepositorio TurmasRep = new TurmaRepositorio();

        // GET: Turmas
        public ActionResult Index()
        {
            return View(TurmasRep.ListarTodos().ToList());
        }

        public ActionResult ActionDeVoltar(string returnUrl)
        {
            if (returnUrl != "")
                return Redirect(returnUrl);
            else
                return null;
        }


        // GET: Turmas/Create
        public ActionResult Create(Guid ModuloId)
        {
            TurmaViewModel turma = new TurmaViewModel() { ModuloId = ModuloId };
            return View();
        }

        // POST: Turmas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModuloId,Inicio,Fim,Nome,Codigo")] TurmaViewModel turma)
        {
            if (ModelState.IsValid)
            {
                Modulo modulo = db.Moduloes.Find(turma.ModuloId);
                Turma turmadb = new Turma()
                {
                    Id = Guid.NewGuid(),
                    Inicio = turma.Inicio,
                    Fim = turma.Fim,
                    Nome = turma.Nome,
                    Codigo = turma.Codigo
                };
                modulo.Turmas.Add(turmadb);
                TurmasRep.Adicionar(turmadb);
                db.SaveChanges();
                //TurmasRep.SalvarTodos();

                return RedirectToAction("Edit", "Modulos", new { id = turma.ModuloId });
            }

            return View(turma);
        }

        // GET: Turmas/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = TurmasRep.Buscar(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // POST: Turmas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Inicio,Fim,Nome,Codigo")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                TurmasRep.Adicionar(turma);
                TurmasRep.SalvarTodos();

                return RedirectToAction("Index");
            }
            return View(turma);
        }

        // GET: Turmas/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = TurmasRep.Buscar(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // POST: Turmas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Turma turma = TurmasRep.Buscar(id);
            TurmasRep.Excluir(t => t == turma);
            TurmasRep.SalvarTodos();

            return RedirectToAction("Index");
        }

        public ActionResult List(List<Turma> turmas)
        {
            return View(turmas);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                TurmasRep.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Modulos/Create.cshtml
@model SurveyManager.Presentation.MVC4.Models.ModuloViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Adicionar Módulo</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.BlocoId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
                @Html.ActionLink("Voltar", "ActionDeVoltar", null, new { returnUrl = this.Request.UrlReferrer }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Modulos/Delete.cshtml
@model SurveyManager.Domain.Model.Implementation.Modulo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar Módulo</h2>

<h3>Tem certeza que deseja deletar esse módulo?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Deletar" class="btn btn-danger" />
        @Html.ActionLink("Voltar", "ActionDeVoltar", null, new { returnUrl = this.Request.UrlReferrer }, new { @class = "btn btn-default" })
    </div>
    }
</div>

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Modulos/Edit.cshtml
@model SurveyManager.Domain.Model.Implementation.Modulo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Módulo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar " class="btn btn-success" />
                @Html.ActionLink("Voltar", "ActionDeVoltar", null, new { returnUrl = this.Request.UrlReferrer }, new { @class = "btn btn-default" })
            </div>
        </div>

        <div class="form-group">
            @Html.ActionLink("Nova Turma", "Create", "Turmas", new { ModuloId = Model.Id }, new { @class = "btn btn-primary" })
        </div>

        <div class="form-group">
            @Html.Action(
            "List",
            "Turmas",
         new { turmas = Model.Turmas })
        </div>
    </div>
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Modulos/Index.cshtml
@model IEnumerable<SurveyManager.Domain.Model.Implementation.Modulo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listar Módulos</h2>

<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            Bloco
        </th>
        <th>
            Curso
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bloco.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bloco.Curso.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Modulos/List.cshtml
@using SurveyManager.Domain.Model.Implementation
@model IEnumerable<Modulo>

@{Layout = "";}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Modulo modulo in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(i => modulo.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(i => modulo.Nome)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = modulo.Id }, null)
                    |
                    @Html.ActionLink("Excluir", "Delete", new { id = modulo.Id }, null)
                </td>
            </tr>
        }
    </tbody>
</table>