src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Model.Implementation;
using SurveyManager.Domain.Repository;
using SurveyManager.Presentation.MVC4.Models;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ModulosController : Controller
    {
        private Contexto db = new Contexto();
        private readonly ModuloRepositorio ModulosRep = new ModuloRepositorio();

        // GET: Modulos
        public ActionResult Index()
        {
            return View(ModulosRep.ListarTodos().ToList());
        }

        public ActionResult ActionDeVoltar(string returnUrl)
        {
            if (returnUrl != "")
                return Redirect(returnUrl);
            else
                return null;
        }

        // GET: Modulos/Create
        public ActionResult Create(Guid blocoId)
        
        {
            ModuloViewModel modulo = new ModuloViewModel() { BlocoId = blocoId };
            return View(modulo);
        }

        // POST: Modulos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "blocoId,Nome,Codigo")] ModuloViewModel modulo)
        {
            if (ModelState.IsValid)
            {
                Bloco bloco = db.Blocos.Find(modulo.BlocoId);
                Modulo moduloDb = new Modulo()
                {
                    Id = Guid.NewGuid(),
                    Nome = modulo.Nome,
                    Codigo = modulo.Codigo
                };
                bloco.Modulos.Add(moduloDb);
                ModulosRep.Adicionar(moduloDb);
                db.SaveChanges();

                return RedirectToAction("Edit", "Blocos", new { id = modulo.BlocoId });
            }

            return View(modulo);
        }

        // GET: Modulos/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulo modulo = db.Moduloes.Find(id);
            db.Entry(modulo).Collection(b => b.Turmas).Load();
            if (modulo == null)
            {
                return HttpNotFound();
            }
            return View(modulo);
        }

        // POST: Modulos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Codigo")] Modulo modulo)
        {
            if (ModelState.IsValid)
            {
                ModulosRep.Atualizar(modulo);
                ModulosRep.SalvarTodos();

                return RedirectToAction("Index");
            }
            return View(modulo);
        }

        // GET: Modulos/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulo modulo = ModulosRep.Buscar(id);
            if (modulo == null)
            {
                return HttpNotFound();
            }
            return View(modulo);
        }

        // POST: Modulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Modulo modulo = ModulosRep.Buscar(id);
            ModulosRep.Excluir(m => m == modulo);
            ModulosRep.SalvarTodos();

            return RedirectToAction("Index");
        }

        public ActionResult List(List<Modulo> modulos)
        {
            return View(modulos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ModulosRep.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Repository;
using SurveyManager.Domain.Model.Implementation;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    public class UsuariosController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private readonly UsuarioRepositorio UsuarioRep = new UsuarioRepositorio();
        // GET: Usuarios
        public ActionResult Index()
        {
            
            return View(UsuarioRep.ListarTodos().ToList());
        }

        // GET: Usuarios
        public ActionResult ListarAdministrador()
        {
            return View(UsuarioRep.ListarAdms().ToList());
        }

        // GET: Usuarios
        public ActionResult ListarAluno()
        {
            return View(UsuarioRep.ListarAlunos().ToList());
        }

        public ActionResult ActionDeVoltar(string returnUrl)
        {
            if (returnUrl != "")
                return Redirect(returnUrl);
            else
                return null;
        }

        // GET: Usuarios/CreateAluno
        public ActionResult CreateAluno()
        {
            return View();
        }

        // POST: Usuarios/CreateAluno
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAluno([Bind(Include = "Id,Matricula,Nome,Email")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                aluno.Id = Guid.NewGuid();
                UsuarioRep.Adicionar(aluno);
                UsuarioRep.SalvarTodos();

                return RedirectToAction("Index");
            }

            return View(aluno);
        }

        // GET: Usuarios/CreateAdm
        public ActionResult CreateAdministrador()
        {
            return View();
        }

        // POST: Usuarios/CreateAdministrador
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdministrador([Bind(Include = "Id,Matricula,Nome,Email")] Administrador administrador)
        {
            if (ModelState.IsValid)
            {
                administrador.Id = Guid.NewGuid();
                UsuarioRep.Adicionar(administrador);
                UsuarioRep.SalvarTodos();

                return RedirectToAction("ListarAdministrador");
            }

            return View(administrador);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = UsuarioRep.Buscar(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Matricula,Nome,Email")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                UsuarioRep.Atualizar(usuario);
                UsuarioRep.SalvarTodos();

                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = UsuarioRep.Buscar(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Usuario usuario = UsuarioRep.Buscar(id);
            UsuarioRep.Excluir(c => c == usuario);
            UsuarioRep.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                UsuarioRep.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projeto Infnet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Survey Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Estrutura <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Cursos", "index", "Cursos")
                                </li>
                                <li>
                                    @Html.ActionLink("Blocos", "index", "Blocos")
                                </li>
                                <li>
                                    @Html.ActionLink("Módulos", "index", "Modulos")
                                </li>
                                <li>
                                    @Html.ActionLink("Turmas", "index", "Turmas")
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuários <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Administrador", "ListarAdministrador", "Usuarios")
                                </li>
                                <li>
                                    @Html.ActionLink("Aluno", "ListarAluno", "usuarios")
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Projeto Final de Engenharia de Software</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>