src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/BlocosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Repository;
using SurveyManager.Domain.Model.Implementation;
using SurveyManager.Presentation.MVC4.Models;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class BlocosController : Controller
    {
        private Contexto db = new Contexto();
        private readonly BlocosRepositorio BlocosRep = new BlocosRepositorio();
        private readonly CursoRepositorio CursosRep = new CursoRepositorio();

        // GET: Blocoes
        public ActionResult Index()
        {
            //Bloco bloco = db.Blocos.Find(id);
            //db.Entry(bloco).Collection(b => b.Modulos).Load();


            //IQueryable<Curso> cursos = CursosRep.ListarTodos();

            //var blocos = from c in cursos
            //             select c.Blocos


            //     CursosRep.ListarTodos()
            //db.Entry(Curso).Collection(b => b.Blocos).Load();

            return View(BlocosRep.ListarTodos().ToList());
        }

        public ActionResult ActionDeVoltar(string returnUrl)
        {
            if (returnUrl != "")
                return Redirect(returnUrl);
            else
                return null;
        }

        // GET: Blocoes/Create
        public ActionResult Create(Guid cursoId)
        {
            BlocoViewModel bloco = new BlocoViewModel() { CursoId = cursoId };
            return View(bloco);
        }


        // POST: Blocoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome,Codigo,CursoId")] BlocoViewModel bloco)
        {
            if (ModelState.IsValid)
            {
                Curso curso = db.Cursos.Find(bloco.CursoId);
                Bloco blocoDb = new Bloco()
                {
                    Id = Guid.NewGuid(),
                    Nome = bloco.Nome,
                    Codigo = bloco.Codigo
                };
                curso.Blocos.Add(blocoDb);
                BlocosRep.Adicionar(blocoDb);
                db.SaveChanges();

                return RedirectToAction("Edit", "Cursos", new { id =  bloco.CursoId} );
            }

            return View(bloco);
        }

        // GET: Blocoes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bloco bloco = db.Blocos.Find(id);
            db.Entry(bloco).Collection(b => b.Modulos).Load();
            if (bloco == null)
            {
                return HttpNotFound();
            }
            return View(bloco);
        }

        // POST: Blocoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Codigo")] Bloco bloco)
        {
            if (ModelState.IsValid)
            {
                BlocosRep.Atualizar(bloco);
                BlocosRep.SalvarTodos();

                return RedirectToAction("Index");
            }
            return View(bloco);
        }

        // GET: Blocoes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bloco bloco = BlocosRep.Buscar(id);
            if (bloco == null)
            {
                return HttpNotFound();
            }
            return View(bloco);
        }

        // POST: Blocoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Bloco bloco = BlocosRep.Buscar(id);
            BlocosRep.Excluir(b => b == bloco);         
            BlocosRep.SalvarTodos();

            return RedirectToAction("Index");
        }

        public ActionResult List(List<Bloco> blocos)
        {
            return View(blocos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                BlocosRep.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveyManager.Domain.DAO.Shared;
using SurveyManager.Domain.Repository;
using SurveyManager.Domain.Model.Implementation;

namespace SurveyManager.Presentation.MVC4.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CursosController : Controller
    {
        private readonly Contexto db = new Contexto();
        private readonly CursoRepositorio CursosRep = new CursoRepositorio();

        // GET: Cursos
        public ActionResult Index()
        {
            return View(CursosRep.ListarTodos().ToList());
        }

        // GET: Blocos
        public ActionResult ListarBlocos(List<Bloco> blocos)
        {
            return View(blocos);
        }

        // GET: Cursoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cursoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Codigo")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                curso.Id = Guid.NewGuid();
                CursosRep.Adicionar(curso);
                CursosRep.SalvarTodos();
                return RedirectToAction("Index");
            }

            return View(curso);
        }

        // GET: Cursoes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursos.Find(id);
            db.Entry(curso).Collection(c => c.Blocos).Load();
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Cursoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Codigo")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                CursosRep.Atualizar(curso);
                CursosRep.SalvarTodos();
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Cursoes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = CursosRep.Buscar(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Cursoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Curso curso = CursosRep.Buscar(id);
            CursosRep.Excluir(c => c == curso);
            CursosRep.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                CursosRep.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Cursos/AdicionarBloco.cshtml
@model SurveyManager.Domain.Model.Implementation.Bloco

@{
    ViewBag.Title = "AdicionarBloco";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Adicionar Bloco</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">


        @Html.Hidden("id", new { @ViewBag.CodCurso })

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
                @Html.ActionLink("Voltar", "Edit", new { id = @ViewBag.CodCurso }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Cursos/Create.cshtml
@model SurveyManager.Domain.Model.Implementation.Curso

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Adicionar Curso</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
                @Html.ActionLink("Voltar", "index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Cursos/Delete.cshtml
@model SurveyManager.Domain.Model.Implementation.Curso

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar Curso</h2>

<h3>Tem certeza que deseja deletar esse curso?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Voltar", "index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Cursos/Edit.cshtml
@model SurveyManager.Domain.Model.Implementation.Curso

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Curso</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar " class="btn btn-success" />
                @Html.ActionLink("Voltar", "index", null, new { @class = "btn btn-default" })
            </div>
        </div>

        <div class="form-group">
            @Html.ActionLink("Novo Bloco", "Create" ,"Blocos", new { cursoId = Model.Id }, new { @class = "btn btn-primary" })
        </div>

        <div class="form-group">
            @Html.Action(
            "List",
            "Blocos",
            new {blocos = Model.Blocos})
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/SurveyManager/SurveyManager.Presentation.MVC4/Views/Cursos/Index.cshtml
@model IEnumerable<SurveyManager.Domain.Model.Implementation.Curso>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Cursos</h2>

<p>
    @Html.ActionLink("Novo Curso", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>